### ISSUE TITLE
WS2812B should be powered from 5V, not 3V3

### ISSUE THREAD

**Issue by tjfsteele** [wuxx/nanoESP32-C6#11]
The official devkit boards use 5V for the WS2812B, and the datasheet for the WS2812B shows a minimum supply voltage of 3V6. Also, the input data signal should not go higher than the supply voltage, which it will on your design as you're converting it to 5V logic level.

I have checked one of your V1.0 boards and confirmed the WS2812B is indeed being supplied with 3V3 as per your schematic.

**Comment by wuxx** [comment]
Hello, yes, you are right, the next version will optimize this problem

**Comment by CK1-CK** [comment]
> The official devkit boards use 5V for the WS2812B, and the datasheet for the WS2812B shows a minimum supply voltage of 3V6. Also, the input data signal should not go higher than the supply voltage, which it will on your design as you're converting it to 5V logic level.
> 
> I have checked one of your V1.0 boards and confirmed the WS2812B is indeed being supplied with 3V3 as per your schematic.

- Is there a way to rewire the board?
- Is it enough to apply 5 volts to VDD?

<img width="687" height="763" alt="Image" src="https://github.com/user-attachments/assets/9b9ebb72-3652-4fa0-b9ac-601cb95cdd2a" />

**Comment by Gunni** [comment]
I have been using these boards for probably over a year now, no issues on my side.

**Comment by CK1-CK** [comment]
> I have been using these boards for probably over a year now, no issues on my side.

Than you have an other Board Version.

NeoPixel LEDs need more than 3,3V (https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf)

<img width="919" height="541" alt="Image" src="https://github.com/user-attachments/assets/4ffe6312-167b-434c-93a2-737f595c09aa" />

**Comment by blu006** [comment]
😡

Schematic still not fixed.  Here is the bodge fix on the PCB.

![PXL_20260427_065337520.MP.jpg](https://github.com/user-attachments/assets/42f00730-ccc1-48e8-8725-887c34c9f244)

**Comment by tuxcrafter** [comment]
I can not get the LED to work with esphome I have a v1.0 board but no v1711 on my pcb

**Comment by Gunni** [comment]
I just don't understand why you guys are having problems, mine looks identical, same version, same everything, except mine never had LED issues? Maybe too bright if anything... I run it at 20-30%.

<img width="300" alt="back" src="https://github.com/user-attachments/assets/79d2f7b8-0456-42b5-8333-789f7eed1308" />

<img width="300" alt="front" src="https://github.com/user-attachments/assets/1291738a-f6b8-4b92-927f-da56ab903eb5" />

Examples:

<details><summary>esphome</summary>
<p>

```yaml
esphome:
  name: esp32-c6-n16-5ebb2c

  on_boot: 
    then:
      - light.turn_on:
          id: led
          brightness: 20%
          effect: Rainbow

esp32:
  board: esp32-c6-devkitm-1
  flash_size: 16MB
  variant: ESP32C6
  framework:
    type: esp-idf

logger:
  level: DEBUG

light:
  - platform: esp32_rmt_led_strip
    internal: True
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    chipset: ws2812
    id: led
    restore_mode: ALWAYS_ON
    default_transition_length: 0ms
    effects:
      - addressable_rainbow: 
          name: Rainbow
          speed: 1
          width: 1
```

</p>
</details>

<details><summary>espresence</summary>
<p>

In espresence, status led, pin 8, GRB, 1 led... Feels flickery but works fine.

</p>
</details>
