### ISSUE TITLE
Full & Complete pinout diagram for this board please

### ISSUE THREAD

**Issue by Anandababu** [wuxx/nanoESP32-C6#12]
Its very difficult to find the pinout references without this board specific diagram. All the references are pointing to generic boards and chips. 

Is it possible to publish a full and complete pinout diagram for this board please?

**Comment by tvixen** [comment]
I have tried to track down any documentation on this board, but without success, 
It's the worst documented board ever. They did even care to copy any of the original onto their /DOC folder.

**Comment by wuxx** [comment]
Hello, actually just having a schematic is enough for development, because the ESP chip has IOMUX function, and IO and hardware functions can be mapped

**Comment by wuxx** [comment]
This is the official SDK of espressif
https://github.com/espressif/esp-idf

**Comment by tvixen** [comment]
Yes, it is appreciated, but the documentation on this board is really poor. Also, the hardware does not follow the standard on other boards. 
But we get what we pay for.... Next time we just have to pay a little more.

**Comment by MrBran4** [comment]
Next time I'll be paying for one that's not a knockoff - they're not even that much more expensive!

Anyway, if it helps @tvixen the pinout seems to more-or-less match the ESP32-C6-WROOM-1 with two extra pins at the bottom near the usb's and skipping a pin on the right

Found this in the schematic dir of this repo, which matches the markings of the board itself

<img width="1362" alt="Image" src="https://github.com/user-attachments/assets/73f645c6-53fe-4d5f-ab63-a1dad24af372" /> 

The above seems to match the pinout from the official espressif docs (below) but with the differences:
- Extra 5v lines (guessing just vbus) at the bottom next to the USBs
- The NC pin on the chip is skipped on the board, replaced with an extra gnd at the bottom

<img width="472" alt="Image" src="https://github.com/user-attachments/assets/7e7eb9fa-5a88-455d-b5d9-95aa5ba87e65" />

From there, things like spi/etc can be figured out from the espressif docs. Or at least that's my plan - I'll report back here if I manage to burn my house down trying

**Comment by tvixen** [comment]
Thanks for the information.... most appreciated, and yes next time I will be more aware of the quality.

**Comment by Low-Code-Platform** [comment]
Any idea how to call the onboard LED? I’m using the adafruit neopix library in Arduino IDE on pin 8, but no luck.

**Comment by Gunni** [comment]
Just wanted to mention that I was able to control the LED from ESPHome using the following:

```yaml
light:
  - platform: esp32_rmt_led_strip
    internal: True
    rgb_order: GRB
    pin: GPIO8
    num_leds: 1
    chipset: ws2812
    id: esp32_rgb_led
    restore_mode: ALWAYS_OFF
    default_transition_length: 0ms
    initial_state: 
      color_brightness: 11%
      brightness: 11%

# Blink demo?
interval:
  - interval: 
      seconds: 1
    then: 
      - light.toggle: esp32_rgb_led
```

`working > correct` but if something is set wrong, let me know.

p.s. this LED at 100% brightness is really blindingly bright, I typically run them at 11% brightness but I have not had `initial_state` work, i need to set it `on_boot`.
